services:
  backend:
    container_name: mt2107_backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "8022:80"
    environment:
      IS_PROD: 1
      PYTHONUNBUFFERED: "TRUE"
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:alpine
    container_name: mt2107_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

volumes:
  pgdata:
  backend_data: