"""focus_liked

Revision ID: 690a3bc37552
Revises: c57163ce0b9e
Create Date: 2024-10-25 00:45:08.104054

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '690a3bc37552'
down_revision = 'c57163ce0b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('focus_is_liked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'focus_is_liked')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    # ### end Alembic commands ###