"""ban

Revision ID: 2203b9a0f3dd
Revises: 7313b1b0300b
Create Date: 2024-11-02 16:28:45.714615

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2203b9a0f3dd'
down_revision = '7313b1b0300b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('ban_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###