"""timestamp_to_now

Revision ID: 7313b1b0300b
Revises: 56aeae0f9315
Create Date: 2024-11-02 00:19:39.995741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7313b1b0300b'
down_revision = '56aeae0f9315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_focus_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['focus_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_focus_id_fkey', 'users', 'users', ['focus_id'], ['id'])
    # ### end Alembic commands ###