"""focus

Revision ID: c57163ce0b9e
Revises: 714db51dd56e
Create Date: 2024-10-23 22:16:28.631737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c57163ce0b9e'
down_revision = '714db51dd56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('focus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['focus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'focus_id')
    # ### end Alembic commands ###