name: Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_HOST: ${{ vars.SERVER_HOST }}
  SERVER_DIR: ${{ vars.SERVER_DIR }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on github
        run: docker compose build

  build-and-run:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Check connection
        run: whoami

      - name: Sync with server
        run: rsync -avz --exclude='.env' ./ ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:${{ vars.SERVER_DIR }}

      - name: Build
        run: |
          ssh $SERVER_USER@$SERVER_HOST << EOF
            cd $SERVER_DIR
            docker compose build
          EOF

      - name: Run
        run: |
          ssh $SERVER_USER@$SERVER_HOST << EOF
            cd $SERVER_DIR
            docker compose up -d
          EOF